version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.3
    - 2.38.5
    - 2.42.2
  - dependency-name: svelte-check
    versions:
    - 1.2.5
  - dependency-name: gestalt
    versions:
    - 16.9.0
    - 17.1.0
    - 18.0.0
    - 18.1.0
  - dependency-name: svg-to-svelte
    versions:
    - 2.2.0
